version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: app-web
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/sistema_matricula
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345  # Cambia esto si deseas una contraseña diferente
      POSTGRES_DB: sistema_matricula
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

